// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icygktsewiskqfqnwfrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeWdrdHNld2lza3FmcW53ZnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTQyOTgsImV4cCI6MjA2ODQzMDI5OH0.FljL19ykYoQQtKrXE5tPyDTnlHnugbnQNos3YYSGA1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});